# Generated by Django 5.2.4 on 2025-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dietplan_goal_alter_learner_goal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='application_text',
            field=models.TextField(default='', verbose_name='Detailed Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='form_check_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Form Check Video URL'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='has_first_aid_certification',
            field=models.BooleanField(default=False, verbose_name='First Aid Certified'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='passed_safety_quiz',
            field=models.BooleanField(default=False, verbose_name='Passed Safety Quiz'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
