# Generated by Django 5.2.4 on 2025-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mentor_application_text_mentor_form_check_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='form_check_video_url',
            field=models.URLField(default='https://example.com/placeholder', verbose_name='Form Check Video URL'),
            preserve_default=False,
        ),
    ]
